### ISSUE TITLE
Home page form validation

### ISSUE THREAD

**Issue by edgarogh** [WartaPoirier-corp/warta-juge-tes-potes#14]
It is currently possible to create/join a room with an empty username. While this shouldn't cause too much problems, that's still a bit weird and might not be desired.

A fix could be to set a minimum number of characters a username should contain. Since people will usually enter their real name, a low bound like 1 or 2 will make the form as inclusive as possible for people with really short first names. This should be enforced both on the client (`minlength=`) and the server. A maximum length may also be a good idea, although I don't really know how it should be chosen.

Additionally, room IDs could be validated with `minlength=8` and `maxlength=8` on the client, and as a (micro-)optimization, the check _could_ be done on the server before querying the hashmap.

It's a bit complicated to do currently, but if avatars are reworked on in the future (i.e. with a texture atlas), this can also be worth validating.

I can do this work.

**Comment by elegaanz** [comment]
I agree. For usernames, a minimum length of 1 character seems good, there is no reason to make it more restrictive.
