### ISSUE TITLE
Actually generate random room IDs

### ISSUE THREAD

**Issue by elegaanz** [WartaPoirier-corp/warta-juge-tes-potes#3]

**Comment by edgarogh** [comment]
If I'm allowed to over-engineer the algorithm in order to make funny IDs, I'm in ! (I need inspiration though)

**Comment by elegaanz** [comment]
I'm not sure you can have both names that sound funny, that are easy to type, that are unique enough and that aren't easy to guess. You have to generate some random character sequence IMO (which is not funny most of the time).

**Comment by edgarogh** [comment]
:cry:
